---
AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repo to house container images.
Resources:
  ContainerRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "ssm-agent"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPull
            Effect: Allow
            Principal: "*"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
Outputs:
  ContainerRepositoryArn:
    Value: !GetAtt ContainerRepository.Arn
    Export:
      Name: ContainerRepositoryArn
